apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    creationTimestamp: "2019-12-10T23:30:13Z"
    generation: 2
    labels:
      app: prometheus-operator-prometheus
      chart: prometheus-operator-8.5.10
      heritage: Helm
      release: prometheus-operator
    name: prometheus-operator-prometheus
    namespace: prometheus
    resourceVersion: "46440536"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/prometheus/prometheuses/prometheus-operator-prometheus
    uid: 03b3c1a6-1ba5-11ea-aa17-4201ac1f000b
  spec:
    alerting:
      alertmanagers:
      - name: prometheus-operator-alertmanager
        namespace: prometheus
        pathPrefix: /
        port: web
    baseImage: quay.io/prometheus/prometheus
    enableAdminAPI: false
    externalUrl: http://prometheus-operator-prometheus.prometheus:9090
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        release: prometheus-operator
    portName: web
    replicas: 1
    retention: 10d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        app: prometheus-operator
        release: prometheus-operator
    securityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: prometheus-operator-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: prometheus-operator
    version: v2.13.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
