apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - interval: 1s
    port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - "nginx-ingress"
  selector:
    matchLabels:
      app: "nginx-ingress"
